In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier as SkKNN
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))
import importlib, minilearn.classifiers.knn
importlib.reload(minilearn.classifiers.knn)
from minilearn.classifiers.knn import KNeighborsClassifier
from minilearn.preprocessing import StandardScaler, train_test_split
from minilearn.metrics import accuracy_score, f1_score

# Iris dataset is a classic 3-class small problem
X, y = load_iris(return_X_y=True)

# Stratified 80/20 split + standardization fit on train only
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2,
                                          random_state=42, stratify=y)
scaler = StandardScaler().fit(X_tr)
X_tr, X_te = scaler.transform(X_tr), scaler.transform(X_te)


ours = KNeighborsClassifier(n_neighbors=5).fit(X_tr, y_tr)
y_pred_ours = ours.predict(X_te)


theirs = SkKNN(n_neighbors=5).fit(X_tr, y_tr)
y_pred_sk = theirs.predict(X_te)

print(f"Our accuracy:        {accuracy_score(y_te, y_pred_ours):.4f}")
print(f"sklearn accuracy:    {accuracy_score(y_te, y_pred_sk):.4f}")
print(f"Predictions agree?   {np.all(y_pred_ours == y_pred_sk)}")
print(f"Our macro F1:        {f1_score(y_te, y_pred_ours, average='macro'):.4f}")


proba = ours.predict_proba(X_te[:3])
print(f"\npredict_proba on 3 samples (each row should sum to 1):")
print(proba)
print(f"Row sums: {proba.sum(axis=1)}")

Our accuracy:        0.9667
sklearn accuracy:    0.9667
Predictions agree?   True
Our macro F1:        0.9666

predict_proba on 3 samples (each row should sum to 1):
[[0.  0.4 0.6]
 [0.  1.  0. ]
 [0.  0.8 0.2]]
Row sums: [1. 1. 1.]


In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB as SkGNB

import importlib, minilearn.classifiers.naive_bayes
importlib.reload(minilearn.classifiers.naive_bayes)
from minilearn.classifiers.naive_bayes import GaussianNB
from minilearn.preprocessing import train_test_split
from minilearn.metrics import accuracy_score, f1_score

X, y = load_iris(return_X_y=True)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2,
                                          random_state=42, stratify=y)

ours   = GaussianNB().fit(X_tr, y_tr)
theirs = SkGNB().fit(X_tr, y_tr)

y_pred_ours = ours.predict(X_te)
y_pred_sk   = theirs.predict(X_te)

print(f"Our accuracy:      {accuracy_score(y_te, y_pred_ours):.4f}")
print(f"sklearn accuracy:  {accuracy_score(y_te, y_pred_sk):.4f}")
print(f"Predictions agree? {np.all(y_pred_ours == y_pred_sk)}")
print(f"Our macro F1:      {f1_score(y_te, y_pred_ours, average='macro'):.4f}")

# Probability sanity check
proba_ours   = ours.predict_proba(X_te[:3])
proba_sk     = theirs.predict_proba(X_te[:3])
print(f"\nOur predict_proba (first 3):\n{proba_ours.round(4)}")
print(f"\nsklearn predict_proba (first 3):\n{proba_sk.round(4)}")
print(f"Row sums: {proba_ours.sum(axis=1)}")

Our accuracy:      0.9667
sklearn accuracy:  0.9667
Predictions agree? True
Our macro F1:      0.9666

Our predict_proba (first 3):
[[0.     0.0355 0.9645]
 [0.     0.7895 0.2105]
 [0.     0.9849 0.0151]]

sklearn predict_proba (first 3):
[[0.     0.0355 0.9645]
 [0.     0.7895 0.2105]
 [0.     0.9849 0.0151]]
Row sums: [1. 1. 1.]
